# Generated by Django 2.1.5 on 2019-01-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
